version: "3.8"
services:
  # code-server:
  #   container_name: code-server.cxcxc.pri
  #   image: codercom/code-server:4.16.0-debian
  #   volumes:
  #     - "./.config:/home/coder/.config"
  #     - ./application/:/home/coder/project
  #   ports:
  #     - "8080:8080"
  #     - "5000:5000"
  #   env_file:
  #     - ./application/.env    
  #   environment:
  #     - DOCKER_USER=cxcxc
  #     - PASSWORD=123456
  #   entrypoint: /bin/bash -c "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && sudo apt update && sudo apt install -y python3-distutils && python3 get-pip.py && PATH=/home/coder/.local/bin && pip install -r project/requirements.txt && PATH=/usr/lib/code-server/lib/vscode/bin/remote-cli:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games && cd project && code-server --install-extension ms-python.python && /usr/bin/entrypoint.sh --bind-addr 0.0.0.0:8080 ."    
  #   networks:
  #     - cxcxc-comprehensive-lab-network

  db:
    container_name: mysqldb.cxcxc.pri
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"      
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - cxcxc-comprehensive-lab-network

  gcs-emulator:
    container_name: gcs-emulator.cxcxc.pri
    image: fsouza/fake-gcs-server:1.46
    command: ["-scheme", "http"]
    ports:
      - "4443:4443"
    volumes:
      - ./gcsdata:/data
    networks:
      - cxcxc-comprehensive-lab-network

  adminer:
    container_name: adminer.cxcxc.pri
    image: adminer:4.8.1-standalone
    ports:
      - "8081:8080"
    networks:
      - cxcxc-comprehensive-lab-network

networks:
  cxcxc-comprehensive-lab-network:
    driver: bridge
